### PR TITLE
Less disruptive info messages

### PR DESCRIPTION
**Pull request by elatoskinas**
According to the developers, `showInformationMessage` messages are intended to be addressed by the user, as in issue: https://github.com/microsoft/vscode/issues/12615 (therefore it is not possible to auto-dismiss them)

Since the purpose of the status bar is to show less intensive messages, we could show the processing/done processing messages in the status bar instead. Optionally, we could show the 'in progress' message in the status bar, and the 'complete' message as the info message.

@mir-am Let me know what you think.

### CODE REVIEW

**Comment by mir-am** [comment]
@elatoskinas
Based on your idea, I've improved the status bar and the extension's messages as follows:
- At the bottom left, there is a status bar (`Type4Py: (loading-icon) 0 (check-icon) 0`) to show no. of prediction requests in progress and no. of successful prediction requests.
- By clicking on the status bar, it shows an output panel, which contains Type4Py's logs and messages.

Let me know your thoughts.

**Comment by elatoskinas** [comment]
@mir-am The new status bar channel is a nice addition, however, in terms of UX, I think it is more confusing. Right now, the only indication is the following:

image

It is not immediately clear that the two icons refer to "requests pending" and "requests in progress", and if I were a first-time user I would probably have trouble understanding when my file has finished type inference.

I would suggest adding additional text of the last relevant action (i.e. "Type inference for file <x>.py is complete!") to the status bar so that it's more explicitly stated to the user. Otherwise, the idea of an extension-specific status bar is nice.

**Comment by mir-am** [comment]
> @mir-am The new status bar channel is a nice addition, however, in terms of UX, I think it is more confusing. Right now, the only indication is the following:
> 
> image
> 
> It is not immediately clear that the two icons refer to "requests pending" and "requests in progress", and if I were a first-time user I would probably have trouble understanding when my file has finished type inference.
> 
> I would suggest adding additional text of the last relevant action (i.e. "Type inference for file .py is complete!") to the status bar so that it's more explicitly stated to the user. Otherwise, the idea of an extension-specific status bar is nice.

Thanks for the feedback.
I agree that some additional text is needed. However, a long text like "Type inference for file .py is complete!" takes quite a bit of space on the status bar given that users may have other extensions with the status bar.
I would say that we can add "in-progress" and "completed" text next to their icons. Also, there is an output channel "Type4Py" that shows complete logs.

**Comment by mir-am** [comment]
@elatoskinas,
I've addressed your comment. Please check it out again and let me know what you think.
Also, when type inference requested, it shows the Type4Py output channel in the IDE to show the user log messages instead of info windows.

**Comment by elatoskinas** [comment]
@mir-am I agree that the text might become too lengthy, so the current approach you have added is very nice. I think we can keep it in this way and now it will be much more clear because the user will see the terminal immediately.

I have made one small adjustment of rearranging the text (let me know if you are for/against it). The final thing we will need to do is to update the README about the status bar once we release this change.

**Review by mir-am — APPROVED** [review]
We can merge this to the `dev` branch.

**Pull request merged**
